apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: service1
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: service2
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: service3
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
