apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels:
    app: service3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: nginx:latest
        ports:
        - containerPort: 80
